/*
 * cs_backend_rkmpp -- Rockchip RK3588 VEPU580, encode + direct MV/SAD
 * readback via MPP's KEY_MOTION_INFO (CS_MODE_ENCODE_READBACK): no decode
 * pass, unlike lavc_sw. See Docs/codec-stereo-DESIGN.md Sec. 5.1/5.4.
 *
 * IMPORTANT -- empirically-derived, vendor-unconfirmed behavior:
 * MppEncMDBlkInfo's exact semantics are undocumented (confirmed absent from
 * both the public MPP repo and web search at the time this was written; the
 * HAL source only wires a buffer fd to a hardware register, the actual bit
 * layout is generated by the ASIC itself). This is also a widely-hit,
 * unresolved upstream issue, not just something specific to this setup --
 * see github.com/rockchip-linux/mpp issue #825, an independent RK3588 user
 * hitting the same "only half the frame" symptom and the same suspicious
 * "mvy=32" value verbatim.
 *
 * Two characteristics, confirmed deterministic and reproducible (dozens of
 * runs, three synthetic textures including per-pixel noise, all bit-level
 * verified by hand -- see the go/no-go spike,
 * src/backends/spike_mpp_mdinfo.c):
 *
 *   1. VERTICAL: only the top ~half of a frame's 16px MB-rows ever get
 *      written (confirmed at 3 heights: 96/192/384px all split almost
 *      exactly in half, every run). The bottom half's memory is left
 *      untouched. No known workaround yet (Phase 6 TODO: encode in vertical
 *      strips short enough to fall entirely in the "safe" half); this
 *      backend flags every block below that line CS_BLK_NO_MATCH rather
 *      than report unverified/possibly-stale data as real.
 *   2. HORIZONTAL: real motion data only appears at EVEN 16-wide raw block
 *      columns; odd columns carry a fixed value (mvx=248, mvy=32 --
 *      exactly the "mvy=32" from issue #825) while their SAD field still
 *      varies genuinely per-block. Hand-verified at the bit level: for
 *      every odd-column word across dozens of blocks, the upper 16 bits
 *      (mvy plus mvx's high byte) were bit-for-bit identical
 *      (0x207c) while the lower 16 bits (SAD plus mvx's low bit) varied
 *      with content -- ruling out a stride/read bug, which would produce
 *      incoherent garbage, not a clean, semantically-consistent split
 *      between "SAD genuinely computed" and "MV never committed." Reads
 *      as a real silicon/firmware defect in how paired lanes of whatever
 *      parallel ME hardware VEPU580 uses commit their MV output, not a
 *      granularity choice. Worked around by reporting one cell per 32px
 *      column, using the (trustworthy) even column's MV and SAD, and
 *      discarding the odd column's MV entirely.
 *
 *      An earlier revision of this file *retracted* this finding as
 *      "doesn't reproduce" after several runs looked clean -- that
 *      retraction was itself wrong: the check script only looked for the
 *      unrelated 0xAAAAAAAA pre-fill sentinel used to investigate #1, never
 *      for this specific (248, 32) pattern, so it could never have detected
 *      this bug regardless of how many times it ran clean. Once checked
 *      for directly, it reproduced on every single run. If investigating
 *      this further, check for the actual (248, 32) pattern, not just
 *      "non-sentinel."
 *   3. UNITS: mvx/mvy's precision is unclear, and may be entangled with
 *      characteristic #2 above rather than a simple scale factor. A
 *      synthetic +16px per-pixel-noise shift test's genuinely-computed
 *      (even-column) SAD values for interior blocks came back low but
 *      *not zero* (~300-2000, not the 0 a perfect match against
 *      unmodified noise should give), with mvx clustering around 36-54 --
 *      consistent with neither integer-pel (expect ~16) nor a clean
 *      quarter-pel reading (expect ~64). Assumed quarter-pel (H.264's
 *      native in-bitstream precision) for lack of a better default, but
 *      this is a real, unresolved discrepancy, not just measurement noise
 *      from an ambiguous test texture -- re-verify with
 *      tests/test_calibration.c before trusting this backend's numbers,
 *      and don't trust a clean-looking calibration run alone if it can't
 *      also explain the non-zero SAD on an exact-shift synthetic pair.
 *
 * One incidental but important lesson from the same investigation: feeding
 * the encoder pure per-pixel white noise as a synthetic test texture
 * triggered a genuine ASIC "bitstream overflow" hardware reset (visible in
 * dmesg: "mpp_rkvenc2 ... found bitstream overflow") on an under-sized
 * output buffer, because it's essentially incompressible -- worst-case
 * input for a real encoder's buffer/rate assumptions. The output packet
 * buffer below is sized generously (3x the raw frame) as a result.
 *
 * Set the CS_RKMPP_DEBUG environment variable to any value to print every
 * (row, col, sad, mvx, mvy) this backend reads to stderr.
 */

#include "codec_stereo/cs.h"
#include "codec_stereo/cs_util.h"
#include "cs_backend.h"

#include <rockchip/rk_mpi.h>
#include <rockchip/mpp_frame.h>
#include <rockchip/mpp_packet.h>
#include <rockchip/mpp_meta.h>
#include <rockchip/mpp_buffer.h>
#include <rockchip/rk_venc_cfg.h>
#include <rockchip/rk_venc_cmd.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define RK_ALIGN(x, a) (((x) + (a) - 1) & ~((a) - 1))

typedef struct rkmpp_ctx {
    int qp;
    int32_t disparity_offset;

    int cols, rows;       /* block_w=32, block_h=16 grid (see file header #2) */
    int16_t *dx, *dy;
    uint16_t *cost;
    uint8_t *flags;
} rkmpp_ctx;

static cs_backend_caps rkmpp_get_caps(void *vctx) {
    rkmpp_ctx *ctx = (rkmpp_ctx *)vctx;
    (void)ctx;
    cs_backend_caps caps;
    memset(&caps, 0, sizeof caps);
    caps.mode = CS_MODE_ENCODE_READBACK;
    caps.native_block_w = 32; /* real MV only ever committed on even 16px columns */
    caps.native_block_h = 16;
    /* VEPU580's motion search is fixed-function; no MppEncCfg key was found
       to configure or query its range. These are undocumented, conservative
       placeholders pending real measurement (Phase 6). */
    caps.max_search_range_x = 64;
    caps.max_search_range_y = 16;
    caps.mv_min_x = -256; /* MppEncMDBlkInfo.mvx is a 9-bit signed field */
    caps.mv_max_x = 255;
    caps.mv_min_y = -128; /* .mvy is 8-bit signed */
    caps.mv_max_y = 127;
    caps.supports_subpel = 1; /* H.264 quarter-pel, assumed -- see file header */
    caps.cost_metric = CS_COST_SAD;
    return caps;
}

static int rkmpp_init(void *vctx, const cs_config *cfg) {
    rkmpp_ctx *ctx = (rkmpp_ctx *)vctx;

    if (mpp_check_support_format(MPP_CTX_ENC, MPP_VIDEO_CodingAVC) != MPP_OK)
        return -1;

    ctx->qp = 12; /* low QP; see lavc_sw's identical rationale */
    ctx->disparity_offset = cfg->disparity_offset;

    if (cfg->backend_params) {
        const char *p = strstr(cfg->backend_params, "qp=");
        if (p) ctx->qp = atoi(p + 3);
    }
    return 0;
}

static int ensure_buffers(rkmpp_ctx *ctx, int cols, int rows) {
    if (cols == ctx->cols && rows == ctx->rows && ctx->dx) return 0;

    free(ctx->dx); free(ctx->dy); free(ctx->cost); free(ctx->flags);

    size_t n = (size_t)cols * (size_t)rows;
    ctx->dx = (int16_t *)malloc(n * sizeof(int16_t));
    ctx->dy = (int16_t *)malloc(n * sizeof(int16_t));
    ctx->cost = (uint16_t *)malloc(n * sizeof(uint16_t));
    ctx->flags = (uint8_t *)malloc(n * sizeof(uint8_t));
    if (!ctx->dx || !ctx->dy || !ctx->cost || !ctx->flags) {
        free(ctx->dx); ctx->dx = NULL;
        free(ctx->dy); ctx->dy = NULL;
        free(ctx->cost); ctx->cost = NULL;
        free(ctx->flags); ctx->flags = NULL;
        ctx->cols = ctx->rows = 0;
        return -1;
    }
    ctx->cols = cols;
    ctx->rows = rows;
    return 0;
}

static int fill_nv12(MppBuffer buf, const uint8_t *luma, int stride,
                      int w, int h, int hor_stride, int ver_stride) {
    uint8_t *p = (uint8_t *)mpp_buffer_get_ptr(buf);
    if (!p) return -1;
    size_t frm_size = (size_t)hor_stride * ver_stride * 3 / 2;
    mpp_buffer_sync_begin(buf);
    memset(p, 128, frm_size); /* flat chroma; see lavc_sw's identical choice */
    for (int y = 0; y < h; y++)
        memcpy(p + (size_t)y * hor_stride, luma + (size_t)y * stride, (size_t)w);
    mpp_buffer_sync_end(buf);
    return 0;
}

static int rkmpp_extract(void *vctx, const cs_frame *left, const cs_frame *right,
                          cs_mv_field *out) {
    rkmpp_ctx *ctx = (rkmpp_ctx *)vctx;
    const int w = left->width, h = left->height;
    if (right->width != w || right->height != h) return -1;

    /* Reported grid: 32-wide x 16-tall cells (file header #2's paired-lane
       MV-commit defect -- only the even 16px raw column is trustworthy). */
    const int cols = (w + 31) / 32;
    const int rows = (h + 15) / 16;
    if (ensure_buffers(ctx, cols, rows) != 0) return -1;

    /* Raw hardware grid: true 16x16 blocks, used only to index md_info. */
    const int raw_cols = (w + 15) / 16;
    const int raw_rows = (h + 15) / 16;
    /* Undocumented vertical limitation (file header #1): everything from
       here down is left CS_BLK_NO_MATCH rather than reporting unverified
       (possibly stale) memory. */
    const int safe_raw_rows = raw_rows / 2;

    for (int i = 0; i < cols * rows; i++) {
        ctx->dx[i] = 0;
        ctx->dy[i] = 0;
        ctx->cost[i] = 0;
        ctx->flags[i] = (uint8_t)(CS_BLK_NO_MATCH);
    }

    int hor_stride = RK_ALIGN(w, 64);
    int ver_stride = RK_ALIGN(h, 16);
    size_t frm_size = (size_t)hor_stride * ver_stride * 3 / 2;
    size_t pkt_size = (size_t)hor_stride * ver_stride * 3; /* generous; avoid
        the bitstream-overflow hit during the go/no-go spike */
    size_t mdinfo_size = (size_t)(RK_ALIGN(hor_stride, 64) >> 6) *
                         (size_t)(RK_ALIGN(ver_stride, 16) >> 4) * 16;

    int ret = -1;
    MppCtx mctx = NULL;
    MppApi *mpi = NULL;
    MppBufferGroup buf_grp = NULL;
    MppEncCfg cfg = NULL;
    MppBuffer frm_buf_l = NULL, frm_buf_r = NULL, pkt_buf = NULL, md_info = NULL;
    uint8_t *right_shifted = NULL;

    if (mpp_create(&mctx, &mpi) != MPP_OK) goto done;
    if (mpp_init(mctx, MPP_CTX_ENC, MPP_VIDEO_CodingAVC) != MPP_OK) goto done;
    if (mpp_buffer_group_get_internal(&buf_grp, MPP_BUFFER_TYPE_DMA_HEAP) != MPP_OK) goto done;

    if (mpp_buffer_get(buf_grp, &frm_buf_l, frm_size) != MPP_OK) goto done;
    if (mpp_buffer_get(buf_grp, &frm_buf_r, frm_size) != MPP_OK) goto done;
    if (mpp_buffer_get(buf_grp, &pkt_buf, pkt_size) != MPP_OK) goto done;
    if (mpp_buffer_get(buf_grp, &md_info, mdinfo_size) != MPP_OK) goto done;

    if (fill_nv12(frm_buf_l, left->data[0], left->stride[0], w, h, hor_stride, ver_stride) != 0)
        goto done;

    /* Same physical pre-shift trick as lavc_sw: VEPU580 exposes no config
       key to bias its (fixed-function) search center, so re-center a
       large disparity_offset by shifting the right image before encoding
       and letting cs_mv_field_to_disparity add the offset back. */
    const uint8_t *right_luma = right->data[0];
    int right_stride = right->stride[0];
    if (ctx->disparity_offset != 0) {
        right_shifted = (uint8_t *)malloc((size_t)w * h);
        if (!right_shifted) goto done;
        cs_shift_gray8(right->data[0], right->stride[0], right_shifted, w,
                        w, h, -ctx->disparity_offset);
        right_luma = right_shifted;
        right_stride = w;
    }
    if (fill_nv12(frm_buf_r, right_luma, right_stride, w, h, hor_stride, ver_stride) != 0)
        goto done;

    mpp_enc_cfg_init(&cfg);
    if (mpi->control(mctx, MPP_ENC_GET_CFG, cfg) != MPP_OK) goto done;

    mpp_enc_cfg_set_s32(cfg, "prep:width", w);
    mpp_enc_cfg_set_s32(cfg, "prep:height", h);
    mpp_enc_cfg_set_s32(cfg, "prep:hor_stride", hor_stride);
    mpp_enc_cfg_set_s32(cfg, "prep:ver_stride", ver_stride);
    mpp_enc_cfg_set_s32(cfg, "prep:format", MPP_FMT_YUV420SP);

    mpp_enc_cfg_set_s32(cfg, "rc:mode", MPP_ENC_RC_MODE_FIXQP);
    mpp_enc_cfg_set_s32(cfg, "rc:fps_in_flex", 0);
    mpp_enc_cfg_set_s32(cfg, "rc:fps_in_num", 30);
    mpp_enc_cfg_set_s32(cfg, "rc:fps_in_denom", 1);
    mpp_enc_cfg_set_s32(cfg, "rc:fps_out_flex", 0);
    mpp_enc_cfg_set_s32(cfg, "rc:fps_out_num", 30);
    mpp_enc_cfg_set_s32(cfg, "rc:fps_out_denom", 1);
    mpp_enc_cfg_set_s32(cfg, "rc:gop", 2); /* exactly this one I+P pair */

    mpp_enc_cfg_set_s32(cfg, "rc:qp_init", ctx->qp);
    mpp_enc_cfg_set_s32(cfg, "rc:qp_max", ctx->qp);
    mpp_enc_cfg_set_s32(cfg, "rc:qp_min", ctx->qp);
    mpp_enc_cfg_set_s32(cfg, "rc:qp_max_i", ctx->qp);
    mpp_enc_cfg_set_s32(cfg, "rc:qp_min_i", ctx->qp);
    mpp_enc_cfg_set_s32(cfg, "rc:qp_ip", 0);

    mpp_enc_cfg_set_s32(cfg, "codec:type", MPP_VIDEO_CodingAVC);
    mpp_enc_cfg_set_s32(cfg, "h264:profile", 100);
    mpp_enc_cfg_set_s32(cfg, "h264:level", 40);
    mpp_enc_cfg_set_s32(cfg, "h264:cabac_en", 1);
    mpp_enc_cfg_set_s32(cfg, "h264:trans8x8", 0);

    if (mpi->control(mctx, MPP_ENC_SET_CFG, cfg) != MPP_OK) goto done;

    MppBuffer frm_bufs[2] = {frm_buf_l, frm_buf_r};
    for (int i = 0; i < 2; i++) {
        MppFrame frame = NULL;
        MppPacket packet = NULL;
        MppMeta meta = NULL;

        mpp_frame_init(&frame);
        mpp_frame_set_width(frame, w);
        mpp_frame_set_height(frame, h);
        mpp_frame_set_hor_stride(frame, hor_stride);
        mpp_frame_set_ver_stride(frame, ver_stride);
        mpp_frame_set_fmt(frame, MPP_FMT_YUV420SP);
        mpp_frame_set_eos(frame, i == 1 ? 1 : 0);
        mpp_frame_set_buffer(frame, frm_bufs[i]);

        mpp_packet_init_with_buffer(&packet, pkt_buf);
        mpp_packet_set_length(packet, 0);

        meta = mpp_frame_get_meta(frame);
        mpp_meta_set_packet(meta, KEY_OUTPUT_PACKET, packet);
        mpp_meta_set_buffer(meta, KEY_MOTION_INFO, md_info);

        MPP_RET pr = mpi->encode_put_frame(mctx, frame);
        mpp_frame_deinit(&frame);
        if (pr != MPP_OK) goto done;

        MppPacket out_packet = NULL;
        if (mpi->encode_get_packet(mctx, &out_packet) != MPP_OK || !out_packet) goto done;
        mpp_packet_deinit(&out_packet);
    }

    /* md_info now reflects the P-frame (right image) encode. Read raw
       uint32 entries -- not through the bitfield struct; mixed-width
       bitfield layout is implementation-defined, mask/shift explicitly. */
    int debug = getenv("CS_RKMPP_DEBUG") != NULL;

    mpp_buffer_sync_begin(md_info);
    {
        /* md_info's raster row stride is padded to a 64-byte boundary
           (matching MPP's own hor_stride alignment for the picture --
           see mdinfo_size above), i.e. mb_cols_padded 16px-block columns
           per row; may exceed `raw_cols` when hor_stride isn't itself a
           64px multiple. */
        int mb_cols_padded = (RK_ALIGN(hor_stride, 64) >> 6) * 4;
        const uint32_t *md = (const uint32_t *)mpp_buffer_get_ptr(md_info);

        for (int by = 0; by < rows && by < safe_raw_rows; by++) {
            for (int bx = 0; bx < cols; bx++) {
                int raw_c0 = bx * 2; /* even raw column: the only trustworthy MV -- file header #2 */
                if (raw_c0 >= raw_cols) break;

                uint32_t w0 = md[by * mb_cols_padded + raw_c0];
                uint32_t sad = w0 & 0x7FFF;
                int32_t mvx = (int32_t)(w0 << 8) >> 23; /* bits 15..23, sign-extended */
                int32_t mvy = (int32_t)w0 >> 24;         /* bits 24..31, sign-extended */

                if (debug)
                    fprintf(stderr, "DBG row=%d col=%d raw_col=%d sad=%u mvx=%d mvy=%d\n",
                            by, bx, raw_c0, sad, mvx, mvy);

                size_t idx = (size_t)by * cols + bx;
                ctx->dx[idx] = (int16_t)mvx;
                ctx->dy[idx] = (int16_t)mvy;
                ctx->cost[idx] = (uint16_t)sad;
                int clamped = (mvx <= -256 || mvx >= 255 || mvy <= -128 || mvy >= 127);
                ctx->flags[idx] = clamped ? (uint8_t)CS_BLK_CLAMPED : (uint8_t)CS_BLK_OK;
            }
        }
    }
    mpp_buffer_sync_end(md_info);

    out->dx = ctx->dx;
    out->dy = ctx->dy;
    out->cost = ctx->cost;
    out->flags = ctx->flags;
    out->block_w = 32;
    out->block_h = 16;
    out->cols = cols;
    out->rows = rows;
    out->subpel_bits = 2; /* assumed quarter-pel; see file header caveat #3 */
    out->disparity_offset = ctx->disparity_offset;
    ret = 0;

done:
    free(right_shifted);
    if (cfg) mpp_enc_cfg_deinit(cfg);
    if (frm_buf_l) mpp_buffer_put(frm_buf_l);
    if (frm_buf_r) mpp_buffer_put(frm_buf_r);
    if (pkt_buf) mpp_buffer_put(pkt_buf);
    if (md_info) mpp_buffer_put(md_info);
    if (buf_grp) mpp_buffer_group_put(buf_grp);
    if (mctx) mpp_destroy(mctx);
    return ret;
}

static void rkmpp_destroy(void *vctx) {
    rkmpp_ctx *ctx = (rkmpp_ctx *)vctx;
    if (!ctx) return;
    free(ctx->dx); free(ctx->dy); free(ctx->cost); free(ctx->flags);
    free(ctx);
}

static void *rkmpp_create(void) {
    return calloc(1, sizeof(rkmpp_ctx));
}

cs_backend_factory cs_backend_rkmpp_factory(void) {
    cs_backend_factory f;
    memset(&f, 0, sizeof f);
    f.create = rkmpp_create;
    f.mode = CS_MODE_ENCODE_READBACK;
    f.ops.name = "rkmpp";
    f.ops.get_caps = rkmpp_get_caps;
    f.ops.init = rkmpp_init;
    f.ops.extract = rkmpp_extract;
    f.ops.destroy = rkmpp_destroy;
    return f;
}
